# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c37bd441303878424d65ea02336f88fc6d66835c3bf21fe5be01c033f003ac235dc752cc83a3267ef31417bc5d335a1bbc9fb7743c5b9de596b33b8b2f18c3

test:
  secret_key_base: b73484b310fffb778d818ddb4b68c4a8fde50cc8b37747167f91f9f1444046a5686813ff7b03146174eaca055c7b98e4cd59dc670f8b1ccac01e9b831ae00f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
